### PR TITLE
More consistent behavior reference determination.

### LINKED ISSUE #440: failed to resolve Behavior as function()
If a behavior is defined like this

`behaviors: [ 
     MyBehavior({ prop : "value"})
],`

analyzer failed with

> [unknown-polymer-behavior] - Unable to resolve behavior `UNKNOWN`

and polymer build failed

### PR DESCRIPTION
**Pull request by rictic**
Fixes #440

 - [x] CHANGELOG.md has been updated

### CODE REVIEW

File: src/polymer/declaration-property-handlers.ts [hunk 1]
```diff
@@ -16,15 +16,48 @@ import * as estree from 'estree';
...
+        message:
+            `Could not determine behavior name from expression of type ${argNode
+                .type}`,
+        severity: Severity.WARNING,
+        sourceRange: document.sourceRangeForNode(argNode)!
+      }
+    };
+  }
+  return {
+    kind: 'behaviorAssignment' as 'behaviorAssignment',
```
Comment (FredKSchott) [inline src/polymer/declaration-property-handlers.ts]: is this type cast needed? Seems strange but I haven't tried running it.

File: src/polymer/declaration-property-handlers.ts [hunk 2]
```diff
@@ -16,15 +16,48 @@ import * as estree from 'estree';
...
 
 import {analyzeProperties} from './analyze-properties';
 import {ScannedPolymerElement} from './polymer-element';
 
+export type BehaviorAssignmentOrWarning = {
+  kind: 'warning',
+  warning: Warning
+} | {kind: 'behaviorAssignment', assignment: ScannedBehaviorAssignment};
+
+export function getBehaviorAssignmentOrWarning(
```
Comment (FredKSchott) [inline src/polymer/declaration-property-handlers.ts]: This design with two possible return types is interesting to see in TypeScript. I think it's fine as written, but in the future it might be more clear to only return a single behavior assignment type on success, and throw an exception on failure with the `warning` data on it.

File: src/polymer/declaration-property-handlers.ts (hunk 1 above)
Comment (rictic) [inline src/polymer/declaration-property-handlers.ts]: It was needed before I declared the BehaviorAssignmentOrWarning type explicitly. Not needed anymore, removed.

File: src/polymer/declaration-property-handlers.ts (hunk 2 above)
Comment (rictic) [inline src/polymer/declaration-property-handlers.ts]: I prefer this style when I want to be sure that the caller is deliberate about both cases. Exceptions are tricky because they're so invisible, usually undocumented, and generally easy to forget to handle.

Comment (FredKSchott) [inline src/polymer/declaration-property-handlers.ts]: Those are good points! I wish TypeScript had the ability to describe the expected errors that may be thrown by a fn.
