### PR TITLE
fix the mixing description problem, fix bad description formatting

### LINKED ISSUE #501: Mixins descriptions aren't read correctly.

### PR DESCRIPTION
**Pull request by FredKSchott**
- Fixes #501 (Fix good descriptions being overwritten in the mixin scanner.)
- Fixes bad formatting with extra newlines in jsdoc descriptions. There still may be some weirdness going on with how this happens, to be investigated later.
- Changelog updated.

### CODE REVIEW

File: src/polymer/polymer2-mixin-scanner.ts [hunk 1]
```diff
@@ -106,10 +104,10 @@ class MixinVisitor implements Visitor {
     const isMixin = this._hasPolymerMixinDocTag(docs);
     const sourceRange = this._document.sourceRangeForNode(node);
     if (isMixin) {
+      console.log('C', cmment, docs);
```
Comment (rictic) [inline src/polymer/polymer2-mixin-scanner.ts]: console

File: src/javascript/jsdoc.ts [hunk 2]
```diff
@@ -143,15 +144,15 @@ export function removeLeadingAsterisks(description: string): string {
...
- * @return {?Annotation}
  */
 export function parseJsdoc(docs: string): Annotation {
   docs = removeLeadingAsterisks(docs);
   const d = doctrine.parse(
       docs, {unwrap: false, lineNumbers: true, preserveWhitespace: true});
-  return {description: d.description, tags: _tagsToHydroTags(d.tags)};
+  // Strip any leading and trailing newline characters in the
+  // description of multiline comments for readibility.
+  const description = d.description && d.description.replace(/^\n+|\n+$/g, '');
```
Comment (justinfagnani) [inline src/javascript/jsdoc.ts]: I think String.trim() is fine here.

Comment (FredKSchott) [inline src/javascript/jsdoc.ts]: That was my original solution, but `String.trim()` ruins any indentation on the first line (theres a test for this specifically).

File: src/polymer/polymer2-mixin-scanner.ts (hunk 1 above)
Comment (FredKSchott) [inline src/polymer/polymer2-mixin-scanner.ts]: doh, thought I got rid of this.

**Comment by usergenic** [comment]
💣 

```
> tsc && npm test
64         description: docs.description,
                        ~~~~
src/polymer/polymer2-mixin-scanner.ts(64,22): error TS2304: Cannot find name 'docs'.
84         description: docs.description,
                        ~~~~
src/polymer/polymer2-mixin-scanner.ts(84,22): error TS2304: Cannot find name 'docs'.
```
